name: Cypress testcases

on:
    push:
      branches:
        - "*"
        
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Testsuit test
        run: | 
            echo "cool i am second one"