name: SonarQube report analysis and Quality gate on pull request

on:
  pull_request: 
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Run cypress tests
      run: |
       echo "Runninng.."
        

    - name: Build and analyze the project with SonarQube
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
      
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Check quality gate status
      run: |
        RESPONSE=$(curl -s "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=QulityGateTest" -u "${{ secrets.SONAR_TOKEN }}")
        STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
        
        if [ "$STATUS" != "OK" ]; then
          echo "SonarQube Quality Gate Failed !!"
          exit 1
        else
          echo "SonarQube Quality Gate passed !!"
        fi